[alias]
build-web-release = "run --release --features release-tools --bin build_web_release --"

[target.wasm32-wasip1]
rustflags = ["-C", "target-feature=+simd128"]

[target.wasm64-unknown-unknown]
rustflags = ["-C", "target-feature=+simd128"]
